config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: "show_task"

  get "tasks/:id/edit", to: "tasks#edit", as: "tasks_edit"
  patch "tasks/:id", to: "tasks#update", as: "task"

  delete "tasks/:id", to: "tasks#destroy", as: "tasks_delete"

  root "tasks#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    #@task = Task.new(params[:task])
    # Will raise ActiveModel::ForbiddenAttributesError
    @task = Task.new(task_params)
    @task.save
    redirect_to show_task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def edit
  end

  def update
    # @task.update(params[:task])
    @task.update(task_params)
    redirect_to show_task_path(@task)
  end

  def nothing_to_do

  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :difficulty, :duration, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Task Manager 1.0</h1>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :difficulty %>
<%= f.number_field :difficulty %>

<%= f.label :duration %>
<%= f.number_field :duration %>

<%= f.label :done %>
<%= f.check_box :done %>

<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<%= link_to "Add a task", tasks_new_path %>

<% @tasks.each do |task| %>
<h2><%= task.name %></h2>
<p><%= task.duration %></p>
<p><%= task.difficulty %></p>
<p><%= task.done %></p>
<%= link_to "Edit a task", tasks_edit_path(task) %>
<%= link_to "Delete", tasks_delete_path(task), method: :delete %>
<% end %>

app/views/tasks/new.html.erb
<form action="/tasks" method="post">
  <input type="text" name="task[name]" id="name" placeholder="What do you need to do?">
  <input type="integer" name="task[difficulty]" id="difficulty" placeholder="Difficulty rating 1-5">
  <input type="integer" name="task[duration]" id="duration" placeholder="How long will it take (in minutes)">
  <input type="checkbox" name="task[done]" id="done" placeholder="Done?">
  <input type="submit">
</form>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.duration %></p>
<p><%= @task.difficulty %></p>
<p><%= @task.done %></p>
<%= link_to "Add a task", tasks_new_path %>
<%= link_to "Edit a task", tasks_edit_path(@task) %>
<%= link_to "Delete", tasks_delete_path(@task), method: :delete %>